/* COMPONENT - INPUTS */
export const IMAGE_INPUT_CREATED = "IMAGE_INPUT_CREATED";
export const IMAGE_INPUT_UPDATED = "IMAGE_INPUT_UPDATED";
export const INPUT_CREATED = "INPUT_CREATED";
export const INPUT_DELETED = "INPUT_DELETED";
export const INPUT_UPDATED = "INPUT_UPDATED";

/* COMPONENT - MENUS */
export const EXTERNAL_CLICK = "EXTERNAL_CLICK";
export const MENU_CLOSED = "MENU_CLOSED";
export const MENU_OPENED = "MENU_OPENED";

/* COMPONENT - MODALS */
export const MODAL_CLOSED = "MODAL_CLOSED";
export const MODAL_OPENED = "MODAL_OPENED";

/* COMPONENT - OBSERVERS */
export const OBSERVER_CREATED = "OBSERVER_CREATED";
export const OBSERVER_DELETED = "OBSERVER_DELETED";
export const OBSERVER_UPDATED = "OBSERVER_UPDATED";

/* COMPONENT - PANELS */
export const PANEL_CREATED = "PANEL_CREATED";
export const PANEL_DELETED = "PANEL_DELETED";
export const PANEL_UPDATED = "PANEL_UPDATED";

/* DATA - ACCOUNT */
export const ACCOUNT_RETRIEVED = "ACCOUNT_RETRIEVED";
export const USERNAME_UPDATED = "USERNAME_UPDATED";

/* DATA - CART */
export const CART_ITEM_CREATED = "CART_ITEM_CREATED";
export const CART_ITEM_DELETED = "CART_ITEM_DELETED";
export const CART_ITEM_UPDATED = "CART_ITEM_UPDATED";
export const CART_EMPTIED = "CART_EMPTIED";
export const CART_RETRIEVED = "CART_RETRIEVED";

/* DATA - CUSTOMERS */
export const CUSTOMER_CREATED = "CUSTOMER_CREATED";
export const CUSTOMER_DELETED = "CUSTOMER_DELETED";
export const CUSTOMER_UPDATED = "CUSTOMER_UPDATED";
export const CUSTOMER_NAME_UPDATED = "CUSTOMER_NAME_UPDATED";
export const CUSTOMERS_RETRIEVED = "CUSTOMERS_RETRIEVED";
export const CUSTOMERS_INITIALIZED = "CUSTOMERS_INITIALIZED";

/* DATA - EMPLOYEES */
export const EMPLOYEE_CREATED = "EMPLOYEE_CREATED";
export const EMPLOYEE_DELETED = "EMPLOYEE_DELETED";
export const EMPLOYEE_UPDATED = "EMPLOYEE_UPDATED";
export const EMPLOYEE_NAME_UPDATED = "EMPLOYEE_NAME_UPDATED";
export const EMPLOYEES_RETRIEVED = "EMPLOYEES_RETRIEVED";

/* DATA - EXPENSES */
export const EXPENSE_CREATED = "EXPENSE_CREATED";
export const EXPENSE_DELETED = "EXPENSE_DELETED";
export const EXPENSE_UPDATED = "EXPENSE_UPDATED";
export const EXPENSES_RETRIEVED = "EXPENSES_RETRIEVED";
export const EXPENSES_INITIALIZED = "EXPENSES_INITIALIZED";

/* DATA - INFLOWS */
export const INFLOW_CREATED = "INFLOW_CREATED";
export const INFLOW_DELETED = "INFLOW_DELETED";
export const INFLOW_UPDATED = "INFLOW_UPDATED";
export const INFLOWS_RETRIEVED = "INFLOWS_RETRIEVED";
export const INFLOWS_INITIALIZED = "INFLOWS_INITIALIZED";

/* DATA - LISTINGS */
export const LISTING_CREATED = "LISTING_CREATED";
export const LISTING_DELETED = "LISTING_DELETED";
export const LISTING_UPDATED = "LISTING_UPDATED";
export const LISTINGS_RETRIEVED = "LISTINGS_RETRIEVED";
export const LISTINGS_UPDATED = "LISTINGS_UPDATED";

/* DATA - ORDERS */
export const ORDER_CREATED = "ORDER_CREATED";
export const ORDER_DELETED = "ORDER_DELETED";
export const ORDER_UPDATED = "ORDER_UPDATED";
export const ORDER_ITEM_CREATED = "ORDER_ITEM_CREATED";
export const ORDER_ITEM_DELETED = "ORDER_ITEM_DELETED";
export const ORDER_ITEM_UPDATED = "ORDER_ITEM_UPDATED";
export const ORDER_TOTALS_RECALCULATED = "ORDER_TOTALS_RECALCULATED";
export const ORDERS_RETRIEVED = "ORDERS_RETRIEVED";
export const ORDERS_INITIALIZED = "ORDERS_INITIALIZED";

/* DATA - PRODUCTS */
export const FLAVOR_CREATED = "FLAVOR_CREATED";
export const FLAVOR_DELETED = "FLAVOR_DELETED";
export const FLAVOR_UPDATED = "FLAVOR_UPDATED";
export const FLAVOR_QUANTITIES_RECALCULATED = "FLAVOR_QUANTITIES_RECALCULATED";
export const PRODUCT_CREATED = "PRODUCT_CREATED";
export const PRODUCT_DELETED = "PRODUCT_DELETED";
export const PRODUCT_UPDATED = "PRODUCT_UPDATED";
export const PRODUCT_QUANTITY_RECALCULATED = "PRODUCT_QUANTITY_RECALCULATED";
export const PRODUCT_TOTALS_RECALCULATED = "PRODUCT_TOTALS_RECALCULATED";
export const PRODUCTS_INITIALIZED = "PRODUCTS_INITIALIZED";
export const PRODUCTS_RETRIEVED = "PRODUCTS_RETRIEVED";
export const PRODUCTS_UPDATED = "PRODUCTS_UPDATED";

/* DATA - RESET STATE */
export const RESET = "RESET";